[package]
name = "monostate"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
description = "Type that deserializes only from one specific value"
repository = "https://github.com/dtolnay/monostate"
documentation = "https://docs.rs/monostate"
readme = "README.md"
keywords = ["serde", "serialization"]

[dependencies]
monostate-impl = { version = "=0.0.0", path = "impl" }
serde = { version = "1.0", default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
