[package]
name = "monostate"
version = "0.0.0"
edition = "2021"

[dependencies]
monostate-impl = { version = "=0.0.0", path = "impl" }
serde = { version = "1.0", default-features = false }

[workspace]
